DEFAULT_SOURCE_FILEPATH: "reads/"
DEFAULT_DEST_FILEPATH: "results/"
RENAMED_READS_FILEPATH: "renamed_raw_reads/"
TRIMMED_READS_FILEPATH: "trimmed/"
FASTQC_FILEPATH: "allfastqc/"
SPADES_FILEPATH: "spades/"
QUAST_FILEPATH: "quast/"
PROKKA_FILEPATH: "prokka/"
BUSCO_FILEPATH: "busco/"
BARRNAP_FILEPATH: "barrnap/"
SAMPLES_TO_COMPARE_FILEPATH: ""
DREP_FILEPATH: "dRep/"
CHECKM_FILEPATH: "checkM/"
ANTISMASH_FILEPATH: "antismash/"


trim_galore:
  - "--length 60" #Discard reads that became shorter than INT because of either quality or adapter trimming
  - "--trim-n" #Removes Ns from either side of the read.
  - "--illumina" #Illumina adapter

fastqc:
  - "--quiet" #Supress all progress messages on stdout and only report errors.

spades:
  - "--only-assembler" # Runs only assembling (without read error correction)
  - "--careful" #Tries to reduce number of mismatches and short indels

prokka:
  - "--compliant" # Force Genbank/ENA/DDJB compliance
  - "--force"
  # Don't use --prefix

busco:
  - "-l bacteria_odb10"
  - "-f" #Force

barrnap:
  - "--kingdom bac" # from bac euk mito arc (default 'bac')

minumun_16s_allowed: 900

dRep:
  - "-pa 0.90" #ANI threshold to form primary (MASH) clusters
# Don't use -p (threads) or '-g' (genomes or `compare`)

checkM:
  -  "--nt -x" 

antismash:
  - "--cb-general" # Compare identified clusters against a database of antiSMASH-predicted clusters.
  - "--cb-knownclusters" # Compare identified clusters against known gene clusters from the MIBiG database.
  - "--cb-subclusters" # Compare identified clusters against known subclusters responsible for synthesising precursors.
  - "--asf" # Run active site finder analysis.
  - "--pfam2go" # Run Pfam to Gene Ontology mapping module.
  - "--smcog-trees" # Generate phylogenetic trees of sec. met. cluster orthologous groups.
  - "--genefinding-tool none" # Not run genefinding
  - "--verbose" # Print verbose status information to stderr.
  # No cores and logfile

# bigscape:
  # Add yours options here
  # - "--mibig14" # Include BGCs from version 1.4 of MIBiG

ANTISMASH-THREADS: 200
ANTISMASH-DOCKER: "antismash/standalone:6.1.1"
