DEFAULT_SOURCE_FILEPATH: "reads/"
DEFAULT_DEST_FILEPATH: "results/"
RENAMED_READS_FILEPATH: "renamed_raw_reads/"
TRIMMED_READS_FILEPATH: "trimmed/"
FASTQC_FILEPATH: "allfastqc/"
SPADES_FILEPATH: "spades/"
QUAST_FILEPATH: "quast/"
PROKKA_FILEPATH: "prokka/"
BUSCO_FILEPATH: "busco/"
BARRNAP_FILEPATH: "barrnap/"
SAMPLES_TO_COMPARE_FILEPATH: ""
DREP_FILEPATH: "dRep/"
CHECKM_FILEPATH: "checkM/"


trim_galore:
  - "--length 60" #Discard reads that became shorter than INT because of either quality or adapter trimming
  - "--trim-n" #Removes Ns from either side of the read.
  - "--illumina" #Illumina adapter

fastqc:
  - "--quiet" #Supress all progress messages on stdout and only report errors.

spades:
  - "--only-assembler" # Runs only assembling (without read error correction)
  - "--careful" #Tries to reduce number of mismatches and short indels

prokka:
  - "--compliant" # Force Genbank/ENA/DDJB compliance
  - "--force"
  # Don't use --prefix

busco:
  - "-l bacteria_odb10"
  - "-f" #Force

barrnap:
  - "--kingdom bac" # from bac euk mito arc (default 'bac')

minumun_16s_allowed: 900

dRep:
  - "-pa 0.90" #ANI threshold to form primary (MASH) clusters
# Don't use -p (threads) or '-g' (genomes or `compare`)

checkM:
  -  "--nt -x" 
