DEFAULT_SOURCE_FILEPATH : "reads/"
DEFAULT_DEST_FILEPATH : "results/"
RENAMED_READS_FILEPATH : "renamed_raw_reads/"
TRIMMED_READS_FILEPATH : "trimmed/"
FASTQC_FILEPATH : "allfastqc/"
SPADES_FILEPATH : "spades/"
QUAST_FILEPATH : "quast/"
PROKKA_FILEPATH : "prokka/"


trim_galore: 
  - "--length 60" #Discard reads that became shorter than INT because of either quality or adapter trimming
  - "--trim-n" #Removes Ns from either side of the read.
  - "--illumina" #Illumina adapter

fastqc: 
  - "--quiet" #Supress all progress messages on stdout and only report errors.

spades: 
  - "-t 40" 
  - "--only-assembler" 
  - "--careful"

prokka:
  - "--compliant"
  # Don't use --prefix